# 基本設定 (((
	# prefixキーをC-sに変更する
	set -g prefix C-s; unbind C-b
	# ウィンドウ・ペイン番号を1から開始
	set-option -g base-index 1
	set-window-option -g pane-base-index 1
	# ウィンドウ番号を詰める
	set-option -g renumber-windows on
	# ペイン番号の表示時間
	set -g display-panes-time 2000
	# ESCの反応を良くする
	set -s escape-time 0
	# マウス操作を有効にする
	set -g mouse on
# )))

# ステータスライン設定 (((
	# ステータスバーを上部に表示する
	set -g status-position top
	# センタライズ（主にウィンドウ番号など）
	set-option -g status-justify centre
	# バーの色設定 {{{
		set -g status-interval 1
		set -g status-bg colour238
		set -g status-fg colour255
		set-option -g status-left "#[bg=colour242,fg=colour255]#{?client_prefix,#[bg=colour25],} #H #[bg=colour238,fg=colour242]#{?client_prefix,#[fg=colour25],}#[default] "
		set-option -g status-left-length 20
		set-option -g status-right '#[bg=colour253,fg=colour238] #[fg=colour236]#(tmux-wifi)#[bold]#(tmux-battery --tmux)#[bg=colour253,fg=colour236] #[bold]|#[default]#[bg=colour253,fg=colour236] [%Y-%m-%d(%a) %H:%M#[fg=colour246]:%S#[fg=colour236]] '
		set-option -g status-right-length 65
		set-window-option -g window-status-current-format "#[bg=colour172,fg=colour238]#[bg=colour172,fg=colour88,bold]#I: #W #[bg=colour238,fg=colour172]#[default]"
	# }}}
# )))

# キーバインド設定 (((
	# ペイン操作 {{{
		# | でペインを縦に分割する
		bind | split-window -h
		# - でペインを横に分割する
		bind - split-window -v
		# vimのキーバインドでペインを移動する
		bind h select-pane -L
		bind j select-pane -D
		bind k select-pane -U
		bind l select-pane -R
		# vimのキーバインドでペインをリサイズする
		bind -r H resize-pane -L 5
		bind -r J resize-pane -D 5
		bind -r K resize-pane -U 5
		bind -r L resize-pane -R 5
	# }}}
# )))

